import { FreshContext } from "$fresh/server.ts";

const QUESTIONS = [
  "What struggle will kids these days never understand?",
  "What is the worst gift you've ever received?",
  "Dogs or cats?",
  "You have five minutes to hide a paperclip in the office before a detective comes in and tries to find it. If the detective fails to find the paperclip, you get $10,000. Where do you hide the paperclip?",
  "Other than family and friends, what are the five things that are the most important to you?",
  "Thick pizza or thin?",
  "Do you fold your pizza?",
  "If you had to title your autobiography with the last mistake you made, what would it be?",
  "What is the most awful fashion trend that you followed religiously?",
  "If you could compete in the Olympics, which sport would you choose?",
  "What is your guilty pleasure movie?",
  "What is your guilty pleasure song?",
  "What horrible fashion trend do you secretly like?",
  "What emoji do you use the most?",
  "If you could walk into any space preceded by an introductory song, what would it be?",
  "What is your favorite decade and why?",
  "What is the best thing you've bought this year?",
  "Who is your favorite Disney movie character?",
  "What bucket list item do you most want to mark off in the next six months?",
  "What was your favorite class in high school?",
  "What was your favorite class in college?",
  "What was the last thing you ate?",
  "What is your go-to book genre?",
  "What is your go-to movie genre?",
  "What app on your phone or tablet do you use the most?",
  "What is your favorite thing to eat for breakfast?",
  "What is your favorite kitchen gadget?",
  "Which song can you listen to over and over again?",
  "What was your favorite show as a kid?",
  "What is your favorite musical instrument and why?",
  "Does your car have a name? What is it?",
  "What famous person from history would you want with you during a zombie apocalypse?",
  "What was the worst haircut you ever rocked?",
  "What movie made you laugh the most?",
  "What band would you want to play at your funeral?",
  "What was your favorite gym activity in high school, middle school, or elementary school?",
  "What was your least favorite gym activity in high school, middle school, or elementary school?",
  "If you had to write a textbook, what would it be about?",
  "Pop quiz or year-end final?",
  "What is your favorite cookie?",
  "What is your favorite ice cream flavor?",
  "Do you prefer hot chocolate, coffee, or tea?",
  "What do you call your grandparents?",
  "What was your first job?",
  "Would you rather be one of the X-Men or a Power Ranger?",
  "Would you rather join Metallica or the New Kids On The Block?",
  "If Aliens landed to retrieve one of their spies, you'd be the least surprised if it was whom?",
  "How often do you work from bed?",
  "What is your morning routine?",
  "If you're not from this city, how did you end up here?",
  "What's your favorite board game?",
  "Are you a morning person or a night owl?",
  "Sweet or savory?",
  "What food from your childhood that others might find strange do you still eat?",
  "If you had to sing karaoke, what song would you choose?",
  "What was your least favorite childhood chore?",
  "What's your favorite scent?",
  "If you had your own late-night talk show, who would you invite as your first guest?",
  "Road trip or plane trip?",
  "If you were given a plane ticket to anywhere in the world, where would you go?",
  "Snow, sand, or something else?",
  "Mountains or beach?",
  "You're going to sail around the world. What do you name your boat?",
  "What was the worst injury you ever had?",
  "Would you rather be trapped on a deserted island alone or with your worst enemy?",
  "If you could have an unlimited supply of one thing for the rest of your life, what would it be?",
  "What is your cellphone or computer wallpaper and why did you choose it?",
  "What was the first thing you thought about when you woke up this morning?",
  "If you could get rid of any current trend, what would it be and why?",
  "What is something you think is totally overrated?",
  "What is your all-time favorite book?",
  "What is your all-time favorite movie?",
  "What is your go-to music genre?",
  "What is one thing that makes you feel positive in some way?",
  "What is one challenge you're experiencing at the moment?",
  "You're alone in a dark cabin. All you have is one match, an oil lamp, a fireplace, and a candle. Which would you light first?",
  "What is your favorite season of the year?",
  "Do you prefer to travel by planes, trains, or automobiles?",
  "Would you ever ride along in a submersible that was going to the bottom of the Mariana Trench?",
  "What is something you've been thinking about lately that no one has asked you about yet?",
  "What is the silliest thing you are willing to argue about?",
  "What is your favorite joke?",
  "What is the strangest gift you've ever received?",
  "What is the most useless talent you have?",
  "What is the coolest talent you have?",
  "If a genie granted you one wish, what would you wish for?",
  "If you could learn one secret of the universe, which one would you choose?",
  "If you could have any animal as a pet, which one would it be?",
  "What would your personal theme song be?",
  "What was a witty comeback you thought of too late?",
  "Who would you cast to play you in a movie about your life?",
  "Which person — living or dead — would you most like to spend the day with?",
  "What is the craziest impulse buy you've ever made?",
  "What is the silliest thing you believed as a child?",
  "What is your favorite way to waste time?",
  "What is a common-knowledge fact that you only just learned?",
  "What is something new you learned recently?",
  "What is your biggest pet peeve?",
  "In what activity could you best the rest of those here today?",
  "What is your most memorable — good or bad — client/customer story?",
  "In which fictional world would you most like to live?",
  "If your pet could talk, what would it say about you?",
  "If you were a superhero, what would your name or power be?",
  "What is the best prank or practical joke you ever pulled?",
  "Who here is most likely to be an undercover secret agent and why?",
  "Where did you go/what did you do on your last vacation?",
  "Where are you planning on going/what are you planning on doing for your next vacation?",
  "What is the last book you read?",
  "How do you deal with stress?",
  "If you could send a short message to your younger self, what would it be?",
  "What would you want your future self to tell you?",
  "Barring the obvious (food, shelter, water",
  "If you had to give an impromptu 30-minute speech on any topic, what would you talk about?",
  "If you could live in any other real time period, which one would it be and why?",
  "Would you choose comfort or growth?",
  "Would you choose to work at home or work in an office?",
  "Do you prefer to ask permission or ask forgiveness?",
  "Look first or leap first?",
  "Dawn or dusk?",
  "Travel or stay at home?",
  "If you had to go with one, would you choose emails or phone calls?",
  "Would you categorize yourself as a risk-taker or a play-it-safer?",
  "Group work or solo work?",
  "Are you an optimist or a pessimist?",
  "Which do you prefer: coffee break or happy hour?",
  "Would you rather receive a long email or attend a long meeting?",
  "Would you rather attend a concert or a sports game?",
  "Work at home or from a cafe?",
  "As a gift, would you prefer a physical thing or an experience?",
  "Android or iPhone?",
  "Windows, Mac, or Linux?",
  "What is your preferred web browser?",
  "Staying in or going out?",
  "Would you rather attend a team lunch or a team dinner? Why?",
  "Would you rather have a video interview or an in-person interview?",
  "Which would you choose: money or influence?",
  "What is one thing you want to improve about yourself?",
  "What is your learning style?",
  "What most surprised you about working in this industry?",
  "Which of your remote coworkers do you think is the tallest?",
  "If you could be any animal for a week, which would you choose?",
  "What's your favorite thing to do in the summer?",
  "What's your favorite thing to do in the fall?",
  "What's your favorite thing to do in the winter?",
  "If you have pets, what are their names?",
  "When you wake up in the morning, what's the first thing you do?",
  "Show us the most interesting thing you have in your purse, wallet, or bag?",
  "What's the longest time, in a single stretch, that you've ever been in a car/on a bike/ on a plane?",
  "How many keys are on your keyring?",
  "What is one food you can't give up?",
  "What is your favorite outdoor activity?",
  "What is your dream car?",
  "Which do you prefer: white chocolate, dark chocolate, or milk chocolate?",
  "Have you ever written a letter to the editor of, or an article or opinion piece for, the local paper? If so, what was it about?",
  "How many languages do you speak?",
  "Are you good at fixing things?",
  "What is your least favorite fruit?",
  "Have you ever flown in a helicopter?",
  "Have you ever ridden on a dog sled?",
  "Who played at the first live concert you attended?",
  "Have you ever climbed a mountain?",
  "Have you ever run a marathon?",
  "What is your favorite video game?",
  "Have you ever met someone famous?",
  "Do you play a musical instrument? If so, which one?",
  "Can you read music?",
  "What's your go-to pizza topping?",
  "What's the oldest piece of clothing you still wear?",
  "Have you ever been skydiving?",
  "Would you ever try skydiving? Why or why not?",
  "What is your middle name?",
  "Do you prefer dancing with a partner or by yourself?",
  "What is your favorite alcoholic drink?",
  "Tattoos: yes or no?",
  "Would you rather be congratulated publicly or privately?",
  "Would you rather sit at a desk all day or work a physical job?",
  "Would you rather have little wins every day or one big win a month?",
  "Would you rather be in the spotlight or behind the scenes?",
  "Would you rather win the lottery or land your dream job?",
  "What does your home office setup look like?",
  "What is your favorite part of working from home?",
  "What is your least favorite part of working from home?",
  "What does your typical workday lunch consist of?",
  "What is the strangest thing you've ever observed during a Zoom meeting?",
  "Do you ever work from bed?",
  "Do you have any family traditions that you look forward to each year?",
  "What is something you've always wanted to do but haven't done yet?",
  "If you're not originally from this city, how/why did you end up here?",
  "If you had a million dollars, what would be the first thing you bought?",
  "What's something interesting about your family history?",
  "Do you have siblings? How many? Where do you fit in the mix?",
  "What's your biggest fear?",
  "If you could master a new skill in an instant, what would it be?",
  "What fictional family would you be a member of?",
  "Would you choose sweet or savory food?",
  "Do you know how to drive?",
  "Do you know how to drive a car with a manual transmission?",
  "What's the last thing you got in trouble for?",
  "When did you last cry in front of another person?",
  "When did you last cry by yourself?",
];

export const handler = (_req: Request, _ctx: FreshContext): Response => {
  const randomIndex = Math.floor(Math.random() * QUESTIONS.length);
  const body = QUESTIONS[randomIndex];
  return new Response(JSON.stringify({ question: body }));
};
